export const APP_PERMISSIONS = [
  "DASHBOARD",
  "ANALYTICS",
  "SECRETARY",
  "INVENTORY",
  "BANK",
  "TAX",
  "DISTRIBUTION",
  "USERS"
];

export const DEFAULT_USER_PERMISSIONS = ["DASHBOARD", "ANALYTICS", "INVENTORY", "DISTRIBUTION"];
