export const APP_PERMISSIONS = [
  "DASHBOARD",
  "ROSTER",
  "INVENTORY",
  "BANK",
  "DISTRIBUTION",
  "USERS"
];

export const DEFAULT_USER_PERMISSIONS = ["DASHBOARD", "ROSTER", "INVENTORY", "DISTRIBUTION"];
