export const APP_PERMISSIONS = [
  "DASHBOARD",
  "ANALYTICS",
  "DAILY_TASKS",
  "SECRETARY",
  "INVENTORY",
  "BANK",
  "DISTRIBUTION",
  "USERS"
];

export const DEFAULT_USER_PERMISSIONS = ["DASHBOARD", "ANALYTICS", "DAILY_TASKS", "INVENTORY", "DISTRIBUTION"];
